lizardfs: Reworked #1 in reference to #2

diff --git a/lizardfs b/lizardfs
--- a/lizardfs
+++ b/lizardfs
@@ -33,10 +33,12 @@ usage() {
 }
 
 err() {
+	(( DEBUG )) && echo "${date}:ERROR: $*" >> "${d_log}/debug.log"
 	echo -ne $* 1>&2 '\n'
 }
 
 log() {
+	(( DEBUG )) && echo "${date}:OUTPUT: $*" >> "${d_log}/debug.log"
 	echo -ne $* >&1
 }
 
@@ -53,6 +55,10 @@ logSuccess() {
 ismounted() {
 	local MNTPATH="$1"
 
+	if [[ ! -d "${MNTPATH}" ]]; then
+		return 1
+	fi
+
 	local MOUNT=$(findmnt -n "${MNTPATH}" 2>/dev/null | cut -d' ' -f1)
 	if [[ "${MOUNT}" = "${MNTPATH}" ]]; then
 		return 0
@@ -62,7 +68,7 @@ ismounted() {
 }
 
 unmount() {
-	(( DEBUG )) && echo "${date}:DOUNMOUNT: $@" >> "${d_log}/unmount.log"
+	(( DEBUG )) && echo "${date}:DOUNMOUNT: $@" >> "${d_log}/debug.log"
 
 	local MNTPATH="$1"
 
@@ -84,7 +90,7 @@ unmount() {
 }
 
 domount() {
-	(( DEBUG )) && echo "${date}:DOMOUNT: $@" >> "${d_log}/mount.log"
+	(( DEBUG )) && echo "${date}:DOMOUNT: $@" >> "${d_log}/debug.log"
 
 	local MNTPATH="$1"
 	local LFSFOLDER="${MNTPATH##*/}"
@@ -92,12 +98,10 @@ domount() {
 	local f_config=
 	local from_secret=0
 	local msgPassword=
+	local HOST=
 	local PASSWORD=
 
 	# Okay, I want to provision the folder in the root of my LizardFS : each pod bound to a PVC bound to a PV has a folder created (folder name is the PV name bound to the PVC)
-	# Obvisouly you need to have a fuse mountpoint on /mnt pointing to the root of your LizardFS.
-	# TO DO : Automated quickmount -> mkdir -> unmount so all the logic is embedded in the flexvolume driver.
-	mkdir -p "/mnt/$LFSFOLDER"
 
 	# It appears the controllers do a first request on mount with the following arguments :
 	# /var/lib/kubelet/plugins/kubernetes.io/flexvolume/lowet84/lizardfs/mounts/mfs-volume /dev/bounded-local {"host":"mfsmaster","kubernetes.io/fsType":"","kubernetes.io/readwrite":"rw","port":"9421"}
@@ -113,10 +117,10 @@ domount() {
 
 	# /var/lib/kubelet/pods/c6f7f490-6009-11e7-83d0-005056af1192/volumes/lowet84~lizardfs/mfs-volume {"host":"mfsmaster","kubernetes.io/fsType":"","kubernetes.io/readwrite":"rw","port":"9421"}
 	#  $PATH		$JSON_OPTS
-	HOST=$(jq -r '.host // empty' <<<"$2")
 
-	# Error out if 'host' isn't provided
+	HOST=$(jq -r '.host // empty' <<<"$2")
 	if [[ -z "${HOST}" ]]; then
+		# Error out if 'host' isn't provided
 		err '{"status": "Failure", "message": "Cannot mount lizardfs volume without a specified host"}'
 		exit 1
 	fi
@@ -168,9 +172,10 @@ domount() {
 		(( from_secret )) && echo "mfspassword=${PASSWORD}"
 	} > "${f_config}"
 
-        echo "mfsmount -H ${HOST} -P ${PORT} -c ${f_config} -o big_writes,nosuid,nodev,noatime -S ${LFSFOLDER} ${MNTPATH} // JSON: $2" | scrub_password >> "${d_log}/mount.log"
-	if ! mfsmount -H "${HOST}" -P "${PORT}" -c ${f_config} -o big_writes,nosuid,nodev,noatime -S "${LFSFOLDER}" "${MNTPATH}" &> /dev/null; then
-		err '{"status": "Failure", "message": "Failed to mount lizardfs at: '"${MNTPATH}"'}'
+	(( DEBUG )) && echo "${date}:CALL: mfsmount -H ${HOST} -P ${PORT} -c ${f_config} -o big_writes,nosuid,nodev,noatime -S ${LFSFOLDER} ${MNTPATH} // JSON: $2" | scrub_password >> "${d_log}/debug.log"
+	MFSMOUNT_OUTPUT=$(mfsmount -H "${HOST}" -P "${PORT}" -c ${f_config} -o big_writes,nosuid,nodev,noatime -S "${LFSFOLDER}" "${MNTPATH}" 2>&1)
+	if [ "$?" -ne 0 ]; then
+		err '{"status": "Failure", "message": "Failed to mount lizardfs at: '"${MNTPATH}"' :: ['"${MFSMOUNT_OUTPUT}"']"}'
 		exit 1
 	fi
 
@@ -186,7 +191,7 @@ scrub_password() {
 }
 
 if [[ "$op" = "init" ]]; then
-	(( DEBUG )) && echo "${date}:INIT: $@" >> /tmp/mount.log
+	(( DEBUG )) && echo "${date}:INIT: $@" >> "${d_log}/debug.log"
 
 	log '{"status": "Success", "capabilities": {"attach": false, "selinuxRelabel": false}}'
 	exit 0
